# Copyright 2026 Anthropic PBC
# SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from typing import Any

from .base import RuntimeAdapter, RuntimeContractError


_CUSTOM_PLUGINS: dict[str, Any] = {}


def register_custom_runtime(name: str, plugin: Any) -> None:
    """Register a trusted host-side runtime plugin.

    Plugins are platform code, never files generated by an untrusted target
    repository. A plugin must provide ``validate(manifest)``,
    ``required_paths(manifest)``, and ``probe(session)``.
    """
    if not isinstance(name, str) or not name.strip():
        raise ValueError("custom runtime plugin name must be non-empty")
    for method in ("validate", "required_paths", "probe"):
        if not callable(getattr(plugin, method, None)):
            raise TypeError(f"custom runtime plugin must provide {method}()")
    _CUSTOM_PLUGINS[name.strip()] = plugin


def unregister_custom_runtime(name: str) -> None:
    _CUSTOM_PLUGINS.pop(name, None)


def _plugin_for(manifest: dict) -> Any:
    name = manifest["runtime"]["plugin"]
    try:
        return _CUSTOM_PLUGINS[name]
    except KeyError as exc:
        raise RuntimeContractError(
            f"custom runtime plugin {name!r} is not registered"
        ) from exc


class CustomRuntime(RuntimeAdapter):
    profile = "custom"

    def validate_profile(self, manifest: dict) -> None:
        runtime = manifest["runtime"]
        plugin = runtime.get("plugin")
        if not isinstance(plugin, str) or not plugin.strip():
            raise RuntimeContractError(
                "custom runtime requires runtime.plugin"
            )
        _plugin_for(manifest).validate(manifest)

    def required_paths(self, manifest: dict) -> list[tuple[str, bool]]:
        return _plugin_for(manifest).required_paths(manifest)

    def probe(self, session) -> None:
        _plugin_for(session.manifest).probe(session)
